environment:
  matrix:
    - PYTHON: "C:\\Python27"
      nodejs_version: "4.6"
    - PYTHON: "C:\\Python33"
      nodejs_version: "4.6"
    - PYTHON: "C:\\Python34"
      nodejs_version: "6.9"
    - PYTHON: "C:\\Python35"
      nodejs_version: "6.9"
    - PYTHON: "C:\\Python36"
      nodejs_version: "8.9"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - ps: Install-Product node $env:nodejs_version
  - pip install virtualenv
  - virtualenv --clear venv
  - "venv\\Scripts\\activate.bat"
  - pip install coverage
  - pip install -U calmjs
  - python setup.py develop

test_script:
  # run base tests without optional dependencies
  - python -m unittest calmjs.rjs.tests.make_suite
  # run full coverage test suite with all dependencies
  - pip install calmjs.dev
  - coverage run --include=src/* -m unittest calmjs.rjs.tests.make_suite
  - coverage report -m

artifacts:
  - path: dist\*

build: off
